name: "[CICD] Invalidate Cache For Katalon Studio"

on:
  workflow_dispatch:
    inputs:
      cloudfront_id:
        description: CloudFront Id
        required: true
        default: E1S9HCHW5N31CV
      cloudfront_object_paths:
        description: Object Paths to invalidate cache
        required: true
        default: '/latest_v9_version.json'
        
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  AWS_ACCOUNT_ID: "346625874447" # Prod

jobs:
  invalidate_cache:
    runs-on: ubuntu-latest
    name: Invalidate Cache Katalon Studio
    steps:
      - name: Set environment base on branch
        id: set_env
        uses: katalon-studio/katalon-base-actions/actions/get-env@v1
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          qa_branch: develop
          stg_branch: master
    outputs:
      ENV: ${{ inputs.environment || steps.set_env.outputs.ENV }}