name: "[CICD] Invalidate Cache For Katalon"

on:
  push:
    branches:
      - CO-2205
  workflow_dispatch:
    inputs:
      cloudfront_object_paths:
        description: Object Paths to invalidate cache
        required: true
        default: '/latest_v9_version.json'
        
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  AWS_ACCOUNT_ID: "346625874447" # Prod
  CLOUDFRONT_ID: E1S9HCHW5N31CV

jobs:
  invalidate_cache:
    runs-on: ubuntu-latest
    name: Invalidate Cache Katalon
    environment: prod
    env:
      SERVICE_NAME: katalon
    steps:
      - name: Invalidate CloudFront cache
        uses: katalon-studio/katalon-base-actions/actions/invalidate-cloudfront-cache@main
        with:
          aws_account_id: ${{ env.AWS_ACCOUNT_ID }}
          cloudfront_id: ${{ env.CLOUDFRONT_ID }}
          cloudfront_object_paths: ${{ inputs.cloudfront_object_paths }}